language: go

go: 
 - 1.x

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libwebkitgtk-3.0-dev
    - os: osx
      osx_image: xcode8.3

script:
  - cd examples/minimal && make && cd ../..
  - cd examples/minimal-go && go build && cd ../..
