name: CI Pipeline
on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev -y
      - name: Build examples
        run: make WEBVIEW=gtk example
      - name: Lint code
        run: make WEBVIEW=gtk lint
      - name: Run tests
        run: make WEBVIEW=gtk test

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build examples
        run: make WEBVIEW=cocoa example
      - name: Lint code
        run: make WEBVIEW=cocoa lint
      - name: Run tests
        run: make WEBVIEW=cocoa test

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build examples
        run: make WEBVIEW=edge example
      - name: Lint code
        run: make WEBVIEW=edge lint
      - name: Run tests
        run: make WEBVIEW=edge test
